
# Site settings
name: Michelle Zaremskas
email: mzaremskas@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, Ruby, WordPress, Go, Kotlin, Full Stack, Angular, Deep Learning, Startups, Agile"
skills: "Freelance Software Engineer "
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/michelllezaremskas/ 
  - title: twitter
    url: https://twitter.com/seachellemz
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3 # Picture Background
  primary-rgb: "33, 150, 243"
  secondary: 076ab8 # Dark Header Background
  secondary-dark: 29455b # DarkHeader Color
  section-tout: eaf1f1  # Textblock background


# Build settings
markdown: kramdown
permalink: pretty
